### ISSUE TITLE
[BUG] The precompile is not working properly in case of not providing parseConfig and formatOption

### ISSUE THREAD

**Issue by L4tabar** [gherking/gherking#87]
## Summary

After start using the gherking 2.4.0 the precompile is not executable and it fails with the following error:
`TypeError: The given tag format is not valid!
    at Tag.toString (projectPath\node_modules\gherkin-ast\ast\tag.js:129:19)
    at format (projectPath\node_modules\gherkin-formatter\formatters\tagFormatter.js:30:42)
    at format (projectPath\node_modules\gherkin-formatter\formatters\featureFormatter.js:23:45)
    at format (projectPath\node_modules\gherkin-formatter\formatters\gherkinDocumentFormatter.js:13:72)
    at format (projectPath\node_modules\gherkin-formatter\index.js:43:50)
    at projectPath\node_modules\gherkin-io\index.js:95:99
    at Generator.next (<anonymous>)
    at projectPath\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (projectPath\node_modules\tslib\tslib.js:165:16)
`

## Steps to Reproduce

1. Install any "gpc" pacakge (e.g. "gpc-for-loop")
2. Have a precompiler that uses the installed "gpc" compiler
3. Have a feature file with a scenario that has a tag (tag example: @random(random)
4. Run the precompile
5. Observe the behavior

### Expected behavior**

5. The precompile executes without any error and the feature files and the scenarios in them are compiled properly

### Actual behavior**

5. The execution fails with the error mentioned in the summary

## Additional context

The issue occurs if the parseConfig and formatOption is not provided

**Comment by szikszail** [comment]
@L4tabar, please try:
 - gherkin-formatter@1.2.1-beta.9
 - gherkin-ast@3.4.1-beta.7
